server:
  port: 8081
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/users_players_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
